### ISSUE TITLE
Ability to "set date" in time report window

### ISSUE THREAD

**Issue by arnisjuraga** [harvesthq/platform#20]
Hi!

Will it be available in the future, to set Date in time report?
E.g. - today, if I want to report time about Yesterday, I need to report time and then open it in Edit mode in Harvest online, and then change date.

**Comment by katierose4** [comment]
Hi @arnisjuraga,

Unfortunately, we don't have plans to add the ability to set the date in the Platform timer modal. We've heard this from some others as well. I can see how this would be useful so that you don't have to go into Harvest app to update dates of time entries. I'll make note of this, but sorry I don't have better news for you!

Thanks,
Katie

**Comment by Bugagazavr** [comment]
@katierose4 hello, today i wrote a small chrome extension, to create report button on commit lists in my Gitlab. But in many situations, i have no time, to go to on harvestapp and set actually date/time. It would be great if your team provide pass data to frame as item_date ( for example ). I do not need a date field, just pass this data to harvestapp
